services:
  back:
    build: ./back
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "3008:3000"
    environment:
      - NODE_ENV=development
  front:
    build: ./front
    ports:
      - "8080:80"
    volumes:
      - ./front/public:/usr/share/nginx/html:ro